// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQDhESdUUYJExarUAZaIa1-H0toJSqYLQ',
    appId: '1:37440482669:web:cdb7960e41b615fe9cfe64',
    messagingSenderId: '37440482669',
    projectId: 'urbane-app',
    authDomain: 'urbane-app.firebaseapp.com',
    storageBucket: 'urbane-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiDEE8HNGvEs_xxrneBGwQMqMM88hdHqA',
    appId: '1:37440482669:android:e3de1279d281ea839cfe64',
    messagingSenderId: '37440482669',
    projectId: 'urbane-app',
    storageBucket: 'urbane-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRLHobgNV_xqP25Su9quNh6yi0Tk2lTWg',
    appId: '1:37440482669:ios:c6264064623462c09cfe64',
    messagingSenderId: '37440482669',
    projectId: 'urbane-app',
    storageBucket: 'urbane-app.firebasestorage.app',
    iosBundleId: 'com.example.urbaneApp',
  );
}
